### ISSUE TITLE
Problem running basic intro script

### ISSUE THREAD

**Issue by EoinKenny** [tongshuangwu/polyjuice#7] opened 2021-12-01 11:55 UTC
Hi, if I run this

![image](https://user-images.githubusercontent.com/22933434/143433070-a6e5c2a4-1289-4671-b93a-2ba02c26deec.png)

I'm getting the following problem

![image](https://user-images.githubusercontent.com/22933434/143433148-a3d45705-94ca-4ea9-bce4-633ba8255524.png)

Any idea what's wrong? Everything is installed ok

**Comment by vasudev13** [comment] 2021-12-06 00:26
Seems like `return_tensors=True` at line 47 in `generator_helpers.py` might be the issue.  

https://colab.research.google.com/drive/1_TWgvLe2QimCYTR2BoxpzB4iWV-QQViG?usp=sharing

(To reproduce, execute once to crash, from error logs follow the path to `generator_helpers.py` and comment out line `return_tensors=True` argument. Save the change and restart the notebook to run again.)

@tongshuangwu , hope this should work fine for now!

**Comment by tongshuangwu** [comment] 2021-12-06 03:00
Thank you both! Unfortunately I couldn't really reproduce the error; When I ran the code it doesn't really crash.
Could you please let me know what's your environment? Seems to run well on my ubuntu machine, with transformers==4.5.1 or 4.8.2?

**Comment by vasudev13** [comment] 2021-12-06 04:16
Yes, you are right, seems to be an issue with transformers version. Latest version `4.12.5` causes the error.

**Comment by tongshuangwu** [comment] 2021-12-06 06:51
Ah, gotcha. I merged your pull request, so hopefully now it works!

**Closed by tongshuangwu** 2021-12-06 06:51 UTC
